spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://172.17.0.3:3306/tp_music?serverTimezone=UTC
    username: root
  cloud:
    config:
      override-none: true
mybatis-plus:
  mapper-locations=classpath: mappers/*xml

server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
